id: I55A4584A
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:09:01.541785+00:00
last_modified: 2022-12-14 18:09:01.541791+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-04-20T20:53:06.315Z'
  creationid: celso
  eft-text-id: UT22084-080-015
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_431-The_Tantra_of_Candamaharosana-v1
bases:
  DDFC:
    source_metadata: null
    order: 1
    base_file: DDFC.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
